# Generated by Django 4.1.4 on 2023-01-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name': 'География', 'verbose_name_plural': 'География'},
        ),
        migrations.RemoveField(
            model_name='geography',
            name='content',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='title',
        ),
        migrations.AddField(
            model_name='geography',
            name='graph_image',
            field=models.ImageField(default=None, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='geography',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
