# Generated by Django 4.1.4 on 2023-01-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_geography_options_remove_geography_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={},
        ),
    ]
