# Generated by Django 4.1.4 on 2023-01-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_geography_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name': 'Geography', 'verbose_name_plural': 'Geography'},
        ),
    ]
