# Generated by Django 4.1.4 on 2023-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_geography_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='content',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geography',
            name='photo',
            field=models.ImageField(default=True, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geography',
            name='title',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
