# Generated by Django 4.1.4 on 2023-01-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='graph_image',
            field=models.ImageField(default=None, upload_to='demand/'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='graph_image',
            field=models.ImageField(default=None, upload_to='geography/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='graph_image',
            field=models.ImageField(default=None, upload_to='skills/%Y/%m/%d'),
        ),
    ]
