# Generated by Django 4.1.4 on 2023-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_demand_graph_image_alter_geography_graph_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geography',
            old_name='html',
            new_name='table_one',
        ),
        migrations.AddField(
            model_name='geography',
            name='table_two',
            field=models.TextField(default=''),
        ),
    ]
