# Generated by Django 4.1.4 on 2023-01-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_html_geography_table_one_geography_table_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='html',
            new_name='table',
        ),
        migrations.AddField(
            model_name='skills',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
