# Generated by Django 4.1.4 on 2023-01-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_html_skills_table_skills_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=225)),
                ('content', models.TextField(default='')),
                ('number', models.CharField(default='', max_length=5)),
            ],
            options={
                'verbose_name': 'IntroCards',
                'verbose_name_plural': 'IntroCards',
            },
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['-year'], 'verbose_name': 'Skills', 'verbose_name_plural': 'Skills'},
        ),
    ]
