# Generated by Django 4.1.4 on 2023-01-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_introcards_alter_skills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=225)),
                ('content', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'IntroFacts',
                'verbose_name_plural': 'IntroFacts',
            },
        ),
    ]
