# Generated by Django 4.1.4 on 2023-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_introfacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='', max_length=225)),
                ('title', models.CharField(default='', max_length=225)),
                ('subtitle', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'IntroCards',
                'verbose_name_plural': 'IntroCards',
            },
        ),
    ]
